on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

name: R-CMD-check

permissions: read-all

jobs:
  windows:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual")'
